name: LeetCode
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.leetcode.svg
  token: NOT_NEEDED
  base: ""
  plugin_leetcode: pallab1999
  plugin_leetcode_sections: solved, skills, recent
